name: Setup
description: Set up the project

runs:
  using: "composite"
  steps:
    - name: Extract dart version
      uses: blendfactory/dvm-config-action@1efe1a203d0a3a31bffd767b0affb251b54ff6bc # v2.0.0
      id: dvm-config-action

    - name: Set up dart
      uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      with:
        sdk: ${{ steps.dvm-config-action.outputs.dart-sdk-version }}

    - name: Get dependencies
      run: dart pub get
      shell: bash

    - name: Set up melos
      run: |
        ln -s $DART_HOME .dvm/dart_sdk
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION
        melos bootstrap
      shell: bash
