name: update_lint_rules
description: A sample command-line application.
version: 3.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  file: ^7.0.0
  freezed_annotation: ^3.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  pub_semver: ^2.1.4
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.7.5
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  lints: ^5.1.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.21.0
