name: Improve
description: Create a report to help us improve
title: "[Improve]: "
labels: [ "improve", "triage" ]

body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: A clear and concise description.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: |
        <img src="" width="320" />
        <video src="" width="320" />
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Please provide details about your environment.
      value: |
        - Package Version: [e.g. 1.0.0]
        - Flutter Version: [e.g. 3.0.0]
        - Dart Version: [e.g. 2.17.0]
        - Commit SHA: [e.g. 935f5890d2bb6eb8cd8b6cb0cc603e5076f10457]
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
